controllers:
    resource: ../../../src/FP/CodeChallenge/Infrastructure/UI/Web/Symfony/Controller
    type: annotation

kernel:
    resource: ../../../src/FP/CodeChallenge/Infrastructure/UI/Web/Symfony/Kernel.php
    type: annotation
