security:
    providers:
        client_certs:
            memory:
                users:
                    challenge@firmaprofesional.com: 
                        roles: [IS_AUTHENTICATED_FULLY]
                        
    firewalls:
        main:
            anonymous: true
            x509:
                provider: client_certs

    access_control:
          - {  path: ^/home, roles: IS_AUTHENTICATED_FULLY }
          - {  path: ^/, requires_channel: https }
