framework:
    default_locale: es
    translator:
        default_path: '%kernel.project_dir%/../src/FP/CodeChallenge/Infrastructure/UI/Web/Symfony/Resources/translations'
        fallbacks:
            - es
