twig:
    default_path: '%kernel.project_dir%/../src/FP/CodeChallenge/Infrastructure/UI/Web/Symfony/views'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
